# Generated by Django 2.1.7 on 2019-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_first',
            new_name='is_valid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='points',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rank',
        ),
        migrations.AddField(
            model_name='student',
            name='efficiency',
            field=models.IntegerField(default=0),
        ),
    ]
