# Generated by Django 2.1.7 on 2019-03-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20190325_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='efficiency',
            field=models.IntegerField(default=100),
        ),
    ]
