# Generated by Django 2.1.7 on 2019-03-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20190325_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='efficiency',
            field=models.FloatField(default=100.0),
        ),
    ]
