# Generated by Django 2.1.7 on 2019-03-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0003_auto_20190325_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(default='medal', max_length=100)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medal_from', to='encouragement.Medal')),
                ('_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medal_to', to='encouragement.Medal')),
            ],
        ),
    ]
