# Generated by Django 2.1.7 on 2019-03-26 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encouragement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
