# Generated by Django 2.1.7 on 2019-03-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
